# Generated by Django 4.0.5 on 2022-08-11 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openinghours',
            name='friday_end',
        ),
        migrations.RemoveField(
            model_name='openinghours',
            name='friday_open',
        ),
        migrations.RemoveField(
            model_name='openinghours',
            name='friday_start',
        ),
        migrations.RemoveField(
            model_name='openinghours',
            name='saturday_end',
        ),
        migrations.RemoveField(
            model_name='openinghours',
            name='saturday_open',
        ),
        migrations.RemoveField(
            model_name='openinghours',
            name='saturday_start',
        ),
        migrations.RemoveField(
            model_name='openinghours',
            name='sunday_end',
        ),
        migrations.RemoveField(
            model_name='openinghours',
            name='sunday_open',
        ),
        migrations.RemoveField(
            model_name='openinghours',
            name='sunday_start',
        ),
        migrations.RemoveField(
            model_name='openinghours',
            name='thursday_end',
        ),
        migrations.RemoveField(
            model_name='openinghours',
            name='thursday_open',
        ),
        migrations.RemoveField(
            model_name='openinghours',
            name='thursday_start',
        ),
        migrations.RemoveField(
            model_name='openinghours',
            name='tuesday_end',
        ),
        migrations.RemoveField(
            model_name='openinghours',
            name='tuesday_open',
        ),
        migrations.RemoveField(
            model_name='openinghours',
            name='tuesday_start',
        ),
        migrations.RemoveField(
            model_name='openinghours',
            name='wednesday_end',
        ),
        migrations.RemoveField(
            model_name='openinghours',
            name='wednesday_open',
        ),
        migrations.RemoveField(
            model_name='openinghours',
            name='wednesday_start',
        ),
    ]
