# Generated by Django 4.0.5 on 2022-08-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_openinghours_friday_end_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='openinghours',
            old_name='monday_open',
            new_name='if_open',
        ),
        migrations.RemoveField(
            model_name='openinghours',
            name='monday_end',
        ),
        migrations.RemoveField(
            model_name='openinghours',
            name='monday_start',
        ),
        migrations.AddField(
            model_name='openinghours',
            name='day_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Godzina zamknięcia'),
        ),
        migrations.AddField(
            model_name='openinghours',
            name='day_of_week',
            field=models.CharField(default=1, max_length=30, verbose_name='Dzień tygodnia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='openinghours',
            name='day_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Godzina otwarcie'),
        ),
    ]
