# Generated by Django 4.0.5 on 2022-08-11 20:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_monday_open_openinghours_if_open_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nazwa')),
                ('description', models.TextField(blank=True, null=True, verbose_name='opis')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cena (zł)')),
            ],
        ),
        migrations.CreateModel(
            name='Shot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nazwa')),
                ('description', models.TextField(blank=True, null=True, verbose_name='opis')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cena (zł)')),
            ],
        ),
        migrations.CreateModel(
            name='Vodka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nazwa')),
                ('description', models.TextField(blank=True, null=True, verbose_name='opis')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cena (zł)')),
            ],
        ),
        migrations.RenameModel(
            old_name='Dish',
            new_name='Beer',
        ),
        migrations.RenameModel(
            old_name='Alcohol',
            new_name='Coffee',
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='if_open',
            field=models.BooleanField(default=True, help_text='odznacz jeśli zamknięte', verbose_name='Czy otwarte'),
        ),
    ]
